# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: DevOps Apprentice
email: noreply@example.com
description: >- # this means to ignore newlines until "baseurl:"
  "Welcome to my knowledge base where you'll find information about applications and projects
  that I've worked on in my home lab and throughout my career. I hope you find something that
  helps you out or teaches you how to do something new."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devopsapprentice.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  tic0uk
iconURL: /assets/default-icon.png
github: tic0uk
twitter: test
linkedin: in/tim-craig2019/

# Build settings
#theme: minima
theme: jekyll-theme-leaf
plugins:
  - jekyll-feed

include:
  - _headers
  - _redirects
  - _includes
  - _layouts
  - _data
  - _sass
  - _authors
  - about.md
  - index.md
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
